version: '3'

services:

    jenkins:
        build: .
        environment:
            JENKINS_HOST_HOME: /data/jenkins
        volumes:
             - ./var/jenkins_home:/var/jenkins_home
             - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8081:8080

    redmine:
        image: sameersbn/redmine:3.4.4-2
        environment:
            DB_ADAPTER: postgresql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: redmine
            DB_PASS: password
            DB_NAME: redmine_production
        volumes:
             - ./var/redmine_home:/home/redmine/data
        ports:
            - 8082:80
        depends_on:
            - postgres

    postgres:
        image: sameersbn/postgresql:9.6-2
        environment:
            DB_USER: redmine
            DB_PASS: password
            DB_NAME: redmine_production
        volumes:
            - ./var/postgresql:/var/lib/postgresql
