version: '3'

services:

    redmine:
        image: sameersbn/redmine:3.4.4-2
        environment:
            DB_ADAPTER: postgresql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: redmine
            DB_PASS: password
            DB_NAME: redmine_production
            SMTP_ENABLED: "true"
            SMTP_DOMAIN: smtp.gmail.com
            SMTP_HOST: smtp.gmail.com
            SMTP_PORT: 587
            SMTP_USER: mailer@example.com
            SMTP_PASS: password
            SMTP_STARTTLS: "true"
            SMTP_AUTHENTICATION: :plain
        volumes:
            - ./var/redmine_home:/home/redmine/data
        ports:
            - 8082:80
        depends_on:
            - postgres

    postgres:
        image: sameersbn/postgresql:9.6-2
        environment:
            DB_USER: redmine
            DB_PASS: password
            DB_NAME: redmine_production
        volumes:
            - ./var/postgresql:/var/lib/postgresql

    sonarqube:
        image: sonarqube:7.1
        environment:
            SONARQUBE_JDBC_USERNAME: sonar
            SONARQUBE_JDBC_PASSWORD: sonar
            SONARQUBE_JDBC_URL: jdbc:postgresql://postgresonar/sonar
        ports:
            - 9000:9000

    postgresonar:
        image: postgres:10.4-alpine
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - ./var/postgresonar:/var/lib/postgresql

    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        volumes:
            - /path/to/your/logstash:/etc/logstash
