version: '3'

services:

    jenkins:
        image: jenkins/jenkins:2.122
        environment:
            JENKINS_HOST_HOME: ./data/jenkins
        volumes:
             - ./data/jenkins_home:/var/jenkins_home
             - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 8081:8080

    redmine:
        image: redmine:3.4
        volumes:
             - ./data/redmine_home/sqlite:/usr/src/redmine/sqlite
             - ./data/redmine_home/files:/usr/src/redmine/files
             - ./data/redmine_home/public/theme:/usr/src/redmine/public/theme
        ports:
          - 8082:3000
